name = "vocab-app"
compatibility_date = "2024-09-23"
main = "src/index.ts"

[assets]
directory = "./client/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "vocab_db"
database_id = "6a795831-1da2-4f95-9711-2fcd57c8b568"
