name: Feature request
description: Suggest an idea or feature you'd like to see implemented
title: '[Feature Request]: '
labels: [enhancement]
assignees: []

body:
    - type: textarea
      id: motivation
      attributes:
          label: Motivation
          description: Why is this feature important? What problem does it solve?
          placeholder: e.g. It would improve usability at night.
      validations:
          required: false

    - type: textarea
      id: solution
      attributes:
          label: Proposed solution
          description: How do you imagine this feature working?
          placeholder: e.g. Add a toggle in the settings menu to switch themes.
      validations:
          required: true

    - type: textarea
      id: additional
      attributes:
          label: Additional context
          description: Add any other context, screenshots, or references here.
          placeholder: e.g. Related issues, links, or images.
      validations:
          required: false
