name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allows manual triggering

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Install client dependencies
        run: cd client && npm ci --legacy-peer-deps
        
      - name: Build client (required for backend tests)
        run: npm run build:client
        
      - name: Run backend tests
        run: npm run test:backend
        env:
          # Add any environment variables your tests need
          NODE_ENV: test
          
      - name: Test Summary
        if: always()
        run: |
          echo "## 🧪 Backend Test Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Backend tests completed" >> $GITHUB_STEP_SUMMARY

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install root dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Install client dependencies
        run: cd client && npm ci --legacy-peer-deps
        
      - name: Run frontend tests
        run: npm run test:frontend:run
        
      - name: Test Summary
        if: always()
        run: |
          echo "## 🎨 Frontend Test Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Frontend tests completed" >> $GITHUB_STEP_SUMMARY

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Install client dependencies
        run: cd client && npm ci --legacy-peer-deps
        
      - name: Build client (required for backend tests)
        run: npm run build:client
        
      - name: Run all tests
        run: npm run test:all
        env:
          NODE_ENV: test
          
      - name: Test Summary
        if: always()
        run: |
          echo "## 🔄 Integration Test Results" >> $GITHUB_STEP_SUMMARY
          echo "✅ All integration tests completed" >> $GITHUB_STEP_SUMMARY

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Install client dependencies
        run: cd client && npm ci --legacy-peer-deps
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Run client ESLint
        run: cd client && npm run lint
